### ISSUE TITLE
Keep  both the navbar and sidebar content  synchronized and avoid  code redundancy 

### ISSUE THREAD

**Issue by ahmedalsanadi** [Mosnad-Web01/movie-streaming-app-A-Sanadi-A-Nabil-Feras#12]
The current implementation of the Navbar and Sidebar components has duplicated content and structure. This redundancy can lead to maintenance challenges and inconsistencies when updates are made. To enhance code quality and maintainability, it’s essential to synchronize the content displayed in both components and eliminate redundant code.

**Comment by Ahmed-Sitl** [comment]
Good idea, but we need to split everything so none will confused when we try to merge
and I try to keep everything split so when we will abstracte the components for the whole project it will be easy becuse we know now all caces for each componentn
